### ISSUE TITLE
Add support for mediakeys

### ISSUE THREAD

**Issue by jkristell** [twitchyliquid64/usbd-hid#11]
Hi

After realizing that the KeyboardReport class doesn't support media keys I decided to try to implement it for a little demo of a infrared receiver controlling the media player on my PC.

This my first ever encounter with USB and USB descriptors and based on googling and testing until it worked. 

My first attempt was to add a new MediaKeyboardReport https://github.com/twitchyliquid64/usbd-hid/pull/9

Then I decided to just add it to the KeyboardReport, and that seems to work as well. https://github.com/twitchyliquid64/usbd-hid/pull/10

Both branches tested on Linux, and Linux only.

The demo can be found here:

https://github.com/jkristell/infrared/blob/cmd/examples/stm32f103-examples/examples/kbd.rs

If you think this is good enough for adding we should probably add an enum with the keycodes for the Media keys as well.

**Comment by twitchyliquid64** [comment]
I think its good to create a new `MediaKeyboardReport` and leave the keyboard report as-is (it matches the one suggested by the spec).

#9 looks good, feel free to add in the keycode enums there as well.
