### ISSUE TITLE
Add keyboard example

### ISSUE THREAD

**Issue by MarkuBu** [twitchyliquid64/usbd-hid#16]
Hi,
can you add a keyboard example? I want to build a mechanical keyboard with an ARM controller running Rust instead of C

and merry christmas

**Comment by twitchyliquid64** [comment]
Merry Christmas!

From memory @Gentoli was doing some cool stuff, and I found something theyve been working on here: https://github.com/Gentoli/wio-term-hid/blob/a9ecf0acc43e0d1f49c03711888afff91c0c2a70/src/main.rs

Does that help?

**Comment by MarkuBu** [comment]
thanks for the link, but meanwhile I found this

https://github.com/TeXitoi/keyberon

**Comment by mutantbob** [comment]
I have been able to get mouse events to work (using https://github.com/imxrt-rs/imxrt-usbd/blob/4c76b38a0f0c91a2d5f326d001b1cf59a4229d6e/examples/teensy4/src/mouse.rs as a base).  But when I try to modify it to generate keyboard events, my kernel logs errors:

```
[230572.937863]` usb 1-6: input irq status -75 received
[230573.937977] usb 1-6: input irq status -75 received
```
The code I am using is

```

            if false {
                let cmd = usbd_hid::descriptor::MouseReport {
                    x: 4,
                    y: 4,
                    buttons: 0,
                    pan: 0,
                    wheel: 0,
                };
                hid.push_input(&cmd)
            } else {
                let cmd = usbd_hid::descriptor::KeyboardReport {
                    modifier: 0,
                    reserved: 0,
                    leds: 0,
                    keycodes: [0, 0,0,0,0,4],
                };

                hid.push_input(&cmd)
            }.unwrap();
```

I took the `[0,0,0,0,0,4]` from one of the linked examples.  The docstring for `KeyboardReport` does not contain the information I need to construct a proper keystroke (for instance, an `f` key).

**Comment by twitchyliquid64** [comment]
`keycodes` are keyboard scancodes, theres a table here: https://usb.org/sites/default/files/hut1_22.pdf#page=83

So `f` should be usage 9, assuming your system maps an `f` scancode to the `f` character.
