### ISSUE TITLE
MouseReport doesn't work with scroll wheel buttons

### ISSUE THREAD

**Issue by riskable** [twitchyliquid64/usbd-hid#17]
I tried adding a 4th (`1 << 3`) and 5th (`1 << 4`) button to my MouseReport but that doesn't work.  Apparently mouse wheel events (which appear on the host OS as buttons 4 and 5) are special somehow.  Likely the `gen_hid_descriptor` call in `descriptor.rs` needs adjusting but I don't know enough to make adjustments on my own.

Is there a way to change how I'm using this crate so that I can send wheel events?

**Comment by twitchyliquid64** [comment]
Can you show me what you mean?

You can create arbitrary HID reports, but whether they map to how the host system interprets them is a different matter.

**Comment by riskable** [comment]
Well I looked up how to generate correct mouse wheel reports (there's a Word doc here that describes it: https://docs.microsoft.com/en-us/previous-versions/windows/hardware/design/dn613912(v=vs.85)?redirectedfrom=MSDN) and I don't think the way `MouseReport` is setup in usbd-hid can handle it because it's lacking values for "wheel" and "pan".

This was my naive attempt to get it working:

```rust
/// MouseReport describes a report and its companion descriptor than can be used
/// to send mouse movements and button presses to a host.
#[gen_hid_descriptor(
    (collection = APPLICATION, usage_page = GENERIC_DESKTOP, usage = MOUSE) = {
        (collection = PHYSICAL, usage = POINTER) = {
            (usage_page = BUTTON, usage_min = BUTTON_1, usage_max = BUTTON_3) = {
                #[packed_bits 3] #[item_settings data,variable,absolute] buttons=input;
            };
            (usage_page = GENERIC_DESKTOP,) = {
                (usage = X,) = {
                    #[item_settings data,variable,relative] x=input;
                };
                (usage = Y,) = {
                    #[item_settings data,variable,relative] y=input;
                };
            };
            (collection = LOGICAL, usage = MOUSE) = {
                #[item_settings data,variable,relative] resolution=input;
                #[item_settings data,variable,relative] wheel=input;
            };
            (collection = LOGICAL, usage = MOUSE) = {
                // (usage = POINTER,) = {
                    #[item_settings data,variable,relative] resolution=input;
                // };
                // (usage = MOUSE,) = {
                    #[item_settings data,variable,relative] pan=input;
                // };
            };
        };
    }
)]
#[allow(dead_code)]
pub struct MouseReport {
    pub buttons: u8,
    pub x: i8,
    pub y: i8,
    pub resolution: i8,
    pub wheel: i8,
    pub pan: i8,
}
```

Then I sent a report that looked like this:

```rust
let mut mouse_report = MouseReport {
        x: 0,
        y: 0,
        buttons: 0,
        resolution: 1,
        wheel: 1,
        pan: 0,
    };
```

...but that didn't result in any button or scroll events on the host OS at all.

**Comment by twitchyliquid64** [comment]
Hmmmm, that descriptor doesnt seem quite right to me (particularly the duplicate `(collection = LOGICAL, usage = MOUSE)`), but I cant access that file cuz its a docx lol :joy:

**Comment by riskable** [comment]
Aha!  I was trying to find a better example doc for you (that was actually on the web and not some .docx or .pdf, ugh) and discovered *a better way*!  It's *soooooo* much simpler!  It was so simple, in fact that I was able to add a trivial Pull Request (#18) to add support for mouse wheel events to usbd-hid 👍

BTW: The way usbd-hid works with Rust macros on these descriptors is *fantastic*!  Very well-thought out and super cool.  Love it!

**Comment by riskable** [comment]
With the PR merged this issue can now be closed.  Fantastic job all around everyone!  :1st_place_medal:
