### ISSUE TITLE
mouse example panics on macosx atsamd51

### ISSUE THREAD

**Issue by jacobrosenthal** [twitchyliquid64/usbd-hid#3]
Technically I ran it on atsamd51, so not exactly your example, but figure better to discuss here.

the push_mouse_movement unwrap specifically

you can avoid panic
```
        let _ = push_mouse_movement(MouseReport { buttons: 0, x, y });
```

Still doesnt appear as a mouse, but then logging then shows
```
UsbBus::write 3 bytes [0, 0, 5] to ep EndpointAddress(129) -> BUSY trcpt1=false
UsbBus::write 3 bytes [0, 0, 251] to ep EndpointAddress(129) -> BUSY trcpt1=false
```

Maybe if I can get it to recognize better itll read and not be busy? not sure. Just wanted to track somewhere

**Comment by twitchyliquid64** [comment]
What was the panic?

**Comment by twitchyliquid64** [comment]
Unwrapping was probably a mistake as a failure to write is not a fault condition. I'm guessing my USB host is polling faster than my samd21 was able to write, hence I never hit the issue.

**Comment by twitchyliquid64** [comment]
Closing this out as the issue relates to an example in the atsamd repository: Specifically the [lack of error handling](https://github.com/atsamd-rs/atsamd/blob/b2d559c8b5acf3bade921a25fb1a32579641c6b7/boards/itsybitsy_m0/examples/twitching_usb_mouse.rs#L71) for if the outgoing buffer is full.
