### ISSUE TITLE
Can we get a 0.6.1 release?

### ISSUE THREAD

**Issue by riskable** [twitchyliquid64/usbd-hid#48]
My `byteorder` PR (#46) that was just merged corrects a big conflict with `embedded-graphics` and it'd be nice to not have to put:

```toml
usbd-hid = { git = "https://github.com/twitchyliquid64/usbd-hid.git", branch = "master" }
```
...in my `Cargo.toml`.

That is all :smile:

**Comment by twitchyliquid64** [comment]
Done!
