### ISSUE TITLE
Cannot create more than 3 `HIDClass`

### ISSUE THREAD

**Issue by HaoboGu** [twitchyliquid64/usbd-hid#59]
Hello, I'm testing this crate for usbd usages. Everything is fine when I create less than 3 `HIDClass`, but if I create 4 `HIDClass`, the usb device just doesn't work: 

I defined the following 4 `HIDClass`:
![image](https://github.com/twitchyliquid64/usbd-hid/assets/8640918/4b3ab177-7f4f-4764-acf7-7d1cc5bf876c)

No configuration descriptor is send from device:
![image](https://github.com/twitchyliquid64/usbd-hid/assets/8640918/c7ca686a-8419-4fc8-983a-542116e2f931)

The following picture is the worked case, when I created only 3 devices(`hid, consumer_control_hid, custom_hid`):
![image](https://github.com/twitchyliquid64/usbd-hid/assets/8640918/48c3e741-0161-4750-aa4b-e04e1be22f85)

**Comment by twitchyliquid64** [comment]
I forget exactly where in the usb-dev USB stack this limitation is from. Maybe take a look through `usb-device` and whatever peripheral driver crate you are using for that limitation?

I could be mistaken but I dont think this is in `HIDClass`

**Comment by HaoboGu** [comment]
Yeah, I solved the problem. That's hardware's endpoint limitation. I'm closing the issue.
