### ISSUE TITLE
usb-hid-macros version with dependency to newer byteorder is unreleased

### ISSUE THREAD

**Issue by flyaruu** [twitchyliquid64/usbd-hid#70]
Hi, I was trying to build using esp-hal, and got the dependency conflict you seem to have noticed in the following commit:

https://github.com/twitchyliquid64/usbd-hid/commit/76bea16537e1a347df2ebced5b9e1d48f71c9859

The usb-hid crate was released, AFAICT the esb-hid-macros was not. Could that one be released? regards, Frank

**Comment by twitchyliquid64** [comment]
Apologies for the delay, Ive released all crates as `0.8.0`. lmk if that works!

**Comment by flyaruu** [comment]
Excellent! I'll have a look soon!
